FROM postgres:16

RUN apt-get update && apt-get install -y \
    build-essential \
    postgresql-server-dev-16 \
    git \
    && git clone --branch v0.7.0 https://github.com/pgvector/pgvector.git /pgvector \
    && cd /pgvector \
    && make \
    && make install \
    && rm -rf /pgvector \
    && apt-get remove -y build-essential git \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
